export const Data = [
    "(child noises in the background)",
    "Hello, hello?",
    "i need to jump into another call",
    "can everyone go on mute?",
    "could you please get closer to the mic",
    "(load painful echo/feedback)",
    "Next slide please",
    "can we take this offline?",
    "is ___ here?",
    "could you share these slides afterwards?",
    "can somebody grant present rights?",
    "can you email that to everyone?",
    " ",
    "sorry, I had problems logging in",
    "(animal noises in background)",
    "sorry, I couldnt find the coference id",
    "i was having connection issues",
    "i'll have to get back to you",
    "who just joined",
    "sorry something ___ with my calendar",
    "can you see my screen?",
    "Lets wait for ___",
    "will you send the minutes?",
    "sorry I was on Mute",
    "can you repeat that?",
  ];